# Generated by Django 4.2.15 on 2025-02-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualcard",
            name="cvv",
            field=models.CharField(max_length=3),
        ),
    ]
