# Generated by Django 4.2.15 on 2025-02-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Annual interest rate as a decimal (eg. 0.0150 for 1.50%)",
                max_digits=5,
                verbose_name="Interest Rate",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAW", "Withdraw"),
                    ("TRANSFER", "Transfer"),
                    ("INTEREST", "Interest"),
                ],
                max_length=10,
                verbose_name="Transaction Type",
            ),
        ),
    ]
